# Generated by Django 5.2.4 on 2025-08-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
