# Generated by Django 5.2.4 on 2025-08-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
