# Generated by Django 5.2.4 on 2025-08-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
