# Generated by Django 5.2.4 on 2025-08-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0006_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
