# Generated by Django 5.2.4 on 2025-08-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0007_profile_document_type_profile_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
    ]
