# Generated by Django 5.2.4 on 2025-08-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0008_alter_profile_document_type_alter_profile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_document',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AddField(
            model_name='profile',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='document_type',
            field=models.CharField(blank=True, choices=[('паспорт', 'Паспорт')], max_length=30, null=True, verbose_name='Документ'),
        ),
    ]
