# Generated by Django 5.2.4 on 2025-08-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0009_profile_id_document_profile_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document_type',
            field=models.CharField(choices=[('Паспорт', 'Паспорт')], default='паспорт', max_length=30, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_document',
            field=models.CharField(default='', max_length=10, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='inn',
            field=models.CharField(default='', max_length=12, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='', max_length=30, verbose_name='Отчество'),
        ),
    ]
