# Generated by Django 5.2.4 on 2025-08-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0010_alter_profile_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document_type',
            field=models.CharField(choices=[('Паспорт', 'Паспорт')], default='Паспорт', max_length=30, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=12, verbose_name='Номер телефона'),
        ),
    ]
