# Generated by Django 5.2.4 on 2025-08-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0011_alter_profile_document_type_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='price',
            field=models.CharField(default='', max_length=12, verbose_name='Стоимость объекта недвижимости'),
        ),
        migrations.AddField(
            model_name='profile',
            name='price_in_queue',
            field=models.CharField(default='', max_length=12, verbose_name='Стоимость объекта недвижимости при переходе в очередь'),
        ),
        migrations.AddField(
            model_name='profile',
            name='type_of_purchase',
            field=models.CharField(choices=[('Первичный', 'Первичный'), ('Вторичный', 'Вторичный')], default='Первичный', max_length=10, verbose_name='Тип покупки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='document_type',
            field=models.CharField(choices=[('Паспорт', 'Паспорт')], default='Паспорт', max_length=20, verbose_name='Документ'),
        ),
    ]
