# Generated by Django 5.2.4 on 2025-08-24 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0012_profile_price_profile_price_in_queue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True, verbose_name='Дата рождения'),
        ),
    ]
