# Generated by Django 5.2.4 on 2025-08-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0014_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_issue',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата выдачи'),
        ),
    ]
