# Generated by Django 5.2.4 on 2025-08-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0015_profile_date_of_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=None, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_issue',
            field=models.DateField(default=None, null=True, verbose_name='Дата выдачи'),
        ),
    ]
