# Generated by Django 5.2.4 on 2025-08-28 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('personal_account', '0016_alter_profile_birth_date_alter_profile_date_of_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_address',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('reg_country', models.CharField(default='', max_length=50, verbose_name='Страна регистрации')),
                ('reg_region', models.CharField(default='', max_length=50, verbose_name='Регион регистрации')),
                ('reg_city', models.CharField(default='', max_length=30, verbose_name='Город регистрации')),
                ('reg_address', models.CharField(default='', max_length=80, verbose_name='Адрес регистрации')),
                ('reg_street', models.CharField(default='', max_length=50, verbose_name='Улица регистрации')),
                ('reg_postal_code', models.CharField(default='', max_length=6, verbose_name='Почтовый индекс регистрации')),
                ('is_approved', models.BooleanField(default=False, max_length=5, null=True, verbose_name='Подтверждение')),
                ('act_country', models.CharField(default='', max_length=50, verbose_name='Страна фактическая')),
                ('act_region', models.CharField(default='', max_length=50, verbose_name='Регион фактическая')),
                ('act_city', models.CharField(default='', max_length=30, verbose_name='Город фактическая')),
                ('act_address', models.CharField(default='', max_length=80, verbose_name='Адрес фактическая')),
                ('act_street', models.CharField(default='', max_length=50, verbose_name='Улица фактическая')),
                ('act_postal_code', models.CharField(default='', max_length=6, verbose_name='Почтовый индекс фактическая')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='agree_to_terms',
            field=models.BooleanField(default=True, null=True, verbose_name='Согдасие на обработку данных'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_coor',
            field=models.CharField(default='', max_length=17, verbose_name='Номер счёта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=None, max_length=10, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_issue',
            field=models.DateField(default=None, max_length=10, null=True, verbose_name='Дата выдачи'),
        ),
    ]
