# Generated by Django 5.2.4 on 2025-08-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0017_profile_address_profile_agree_to_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parther_name',
            field=models.CharField(default='', max_length=50, verbose_name='Фамилия и имя, пригласившего вас, партнёра'),
        ),
    ]
