# Generated by Django 5.2.4 on 2025-08-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0018_profile_parther_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parther_phone',
            field=models.CharField(default='', max_length=13, verbose_name='Номер телефона пригласителя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=13, verbose_name='Номер телефона'),
        ),
    ]
