# Generated by Django 5.2.4 on 2025-08-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0019_profile_parther_phone_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='price_in_queue',
            field=models.CharField(default='', max_length=12, verbose_name='Стоимость объекта при переходе в очередь'),
        ),
    ]
