# Generated by Django 5.2.4 on 2025-09-02 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0020_alter_profile_price_in_queue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_coor',
            field=models.CharField(default='', max_length=24, verbose_name='Номер счёта'),
        ),
        migrations.AlterField(
            model_name='profile_address',
            name='act_address',
            field=models.CharField(default='', max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='profile_address',
            name='act_city',
            field=models.CharField(default='', max_length=30, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile_address',
            name='act_country',
            field=models.CharField(default='', max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='profile_address',
            name='act_postal_code',
            field=models.CharField(default='', max_length=6, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='profile_address',
            name='act_region',
            field=models.CharField(default='', max_length=50, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='profile_address',
            name='act_street',
            field=models.CharField(default='', max_length=50, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='profile_address',
            name='reg_address',
            field=models.CharField(default='', max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='profile_address',
            name='reg_city',
            field=models.CharField(default='', max_length=30, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile_address',
            name='reg_country',
            field=models.CharField(default='', max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='profile_address',
            name='reg_postal_code',
            field=models.CharField(default='', max_length=6, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='profile_address',
            name='reg_region',
            field=models.CharField(default='', max_length=50, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='profile_address',
            name='reg_street',
            field=models.CharField(default='', max_length=50, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='profile_address',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_address', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
