# Generated by Django 5.2.4 on 2025-09-06 11:48

import django.core.validators
import personal_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0021_alter_profile_id_coor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_coor',
            field=models.CharField(default='', max_length=24, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z-]+$', 'Номер счёта может содержать только цифры и латинские буквы')], verbose_name='Номер счёта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_document',
            field=models.CharField(default='', max_length=10, validators=[personal_account.models.validate_passport], verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='inn',
            field=models.CharField(default='', max_length=12, validators=[personal_account.models.validate_inn], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parther_name',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁ\\s]+$', 'ФИО может содержать только русские буквы и пробелы')], verbose_name='Фамилия и имя партнёра'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parther_phone',
            field=models.CharField(default='', max_length=13, validators=[personal_account.models.validate_phone], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=13, validators=[personal_account.models.validate_phone], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.CharField(default='', max_length=12, validators=[personal_account.models.validate_price], verbose_name='Стоимость объекта недвижимости'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price_in_queue',
            field=models.CharField(default='', max_length=12, validators=[personal_account.models.validate_price], verbose_name='Стоимость объекта при переходе в очередь'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁ\\s]+$', 'Отчество может содержать только русские буквы, пробелы и дефисы')], verbose_name='Отчество'),
        ),
    ]
