# Generated by Django 5.2.4 on 2025-09-06 11:51

import personal_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0022_alter_profile_id_coor_alter_profile_id_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='parther_phone',
            field=models.CharField(default='', max_length=12, validators=[personal_account.models.validate_phone], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=12, validators=[personal_account.models.validate_phone], verbose_name='Номер телефона'),
        ),
    ]
