# Generated by Django 5.2.4 on 2025-09-06 12:30

import personal_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0023_alter_profile_parther_phone_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_address',
            name='act_apartament',
            field=models.CharField(default='', max_length=20, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='profile_address',
            name='act_house',
            field=models.CharField(default='', max_length=20, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='profile_address',
            name='reg_apartament',
            field=models.CharField(default='', max_length=20, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='profile_address',
            name='reg_house',
            field=models.CharField(default='', max_length=20, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='profile_address',
            name='act_postal_code',
            field=models.CharField(default='', max_length=6, validators=[personal_account.models.validate_postal_code], verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='profile_address',
            name='reg_postal_code',
            field=models.CharField(default='', max_length=6, validators=[personal_account.models.validate_postal_code], verbose_name='Почтовый индекс'),
        ),
    ]
