# Generated by Django 5.2.4 on 2025-09-07 12:43

import django.core.validators
import personal_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0024_profile_address_act_apartament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document_photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=personal_account.models.profile_doc_upload_path, validators=[personal_account.models.clean_document_photo], verbose_name='Фото документа'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_coor',
            field=models.CharField(default='', max_length=24, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z-]+$', 'Номер счёта может содержать только цифры и латинские буквы и дефис')], verbose_name='Номер счёта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_document',
            field=models.CharField(default='', max_length=11, validators=[personal_account.models.validate_passport], verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parther_name',
            field=models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁ\\s]+$', 'ФИО партнёра может содержать только русские буквы и пробелы')], verbose_name='Фамилия и имя партнёра'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁ]+$', 'Отчество может содержать только русские буквы')], verbose_name='Отчество'),
        ),
    ]
