# Generated by Django 5.2.4 on 2025-09-07 15:34

import django.core.validators
import django.db.models.deletion
import personal_account.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0025_profile_document_photo_alter_profile_id_coor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_edit',
            field=models.BooleanField(default=True, verbose_name='Разрешено редактирование'),
        ),
        migrations.CreateModel(
            name='HistoricalProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('surname', models.CharField(default='', max_length=30, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁ]+$', 'Отчество может содержать только русские буквы')], verbose_name='Отчество')),
                ('phone', models.CharField(default='', max_length=12, validators=[personal_account.models.validate_phone], verbose_name='Номер телефона')),
                ('agree_to_terms', models.BooleanField(default=True, null=True, verbose_name='Согдасие на обработку данных')),
                ('document_type', models.CharField(choices=[('Паспорт', 'Паспорт')], default='Паспорт', max_length=20, verbose_name='Документ')),
                ('id_document', models.CharField(default='', max_length=11, validators=[personal_account.models.validate_passport], verbose_name='Серия и номер паспорта')),
                ('inn', models.CharField(default='', max_length=12, validators=[personal_account.models.validate_inn], verbose_name='ИНН')),
                ('type_of_purchase', models.CharField(choices=[('Первичный', 'Первичный'), ('Вторичный', 'Вторичный')], default='Первичный', max_length=10, verbose_name='Тип покупки')),
                ('price', models.CharField(default='', max_length=12, validators=[personal_account.models.validate_price], verbose_name='Стоимость объекта недвижимости')),
                ('price_in_queue', models.CharField(default='', max_length=12, validators=[personal_account.models.validate_price], verbose_name='Стоимость объекта при переходе в очередь')),
                ('birth_date', models.DateField(default=None, max_length=10, null=True, verbose_name='Дата рождения')),
                ('date_of_issue', models.DateField(default=None, max_length=10, null=True, verbose_name='Дата выдачи')),
                ('id_coor', models.CharField(default='', max_length=24, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z-]+$', 'Номер счёта может содержать только цифры и латинские буквы и дефис')], verbose_name='Номер счёта')),
                ('parther_name', models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁ\\s]+$', 'ФИО партнёра может содержать только русские буквы и пробелы')], verbose_name='Фамилия и имя партнёра')),
                ('parther_phone', models.CharField(default='', max_length=12, validators=[personal_account.models.validate_phone], verbose_name='Номер телефона')),
                ('document_photo', models.TextField(blank=True, default='', max_length=100, null=True, validators=[personal_account.models.clean_document_photo], verbose_name='Фото документа')),
                ('can_edit', models.BooleanField(default=True, verbose_name='Разрешено редактирование')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical profile',
                'verbose_name_plural': 'historical profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
