# Generated by Django 5.2.4 on 2025-09-14 18:59

import django.core.validators
import personal_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0026_profile_can_edit_historicalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='birth_date',
            field=models.DateField(blank=True, default=None, max_length=10, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='date_of_issue',
            field=models.DateField(blank=True, default=None, max_length=10, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='id_coor',
            field=models.CharField(blank=True, default='', max_length=24, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z-]+$', 'Номер счёта может содержать только цифры и латинские буквы и дефис')], verbose_name='Номер счёта'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='id_document',
            field=models.CharField(blank=True, default='', max_length=11, validators=[personal_account.models.validate_passport], verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=12, validators=[personal_account.models.validate_inn], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='parther_name',
            field=models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁ\\s]+$', 'ФИО партнёра может содержать только русские буквы и пробелы')], verbose_name='Фамилия и имя партнёра'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=12, validators=[personal_account.models.validate_phone], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='price',
            field=models.CharField(blank=True, default='', max_length=12, validators=[personal_account.models.validate_price], verbose_name='Стоимость объекта недвижимости'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='price_in_queue',
            field=models.CharField(blank=True, default='', max_length=12, validators=[personal_account.models.validate_price], verbose_name='Стоимость объекта при переходе в очередь'),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=30, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁ]+$', 'Отчество может содержать только русские буквы')], verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=None, max_length=10, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_issue',
            field=models.DateField(blank=True, default=None, max_length=10, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_coor',
            field=models.CharField(blank=True, default='', max_length=24, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z-]+$', 'Номер счёта может содержать только цифры и латинские буквы и дефис')], verbose_name='Номер счёта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_document',
            field=models.CharField(blank=True, default='', max_length=11, validators=[personal_account.models.validate_passport], verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=12, validators=[personal_account.models.validate_inn], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parther_name',
            field=models.CharField(blank=True, default='', max_length=50, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁ\\s]+$', 'ФИО партнёра может содержать только русские буквы и пробелы')], verbose_name='Фамилия и имя партнёра'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=12, validators=[personal_account.models.validate_phone], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.CharField(blank=True, default='', max_length=12, validators=[personal_account.models.validate_price], verbose_name='Стоимость объекта недвижимости'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price_in_queue',
            field=models.CharField(blank=True, default='', max_length=12, validators=[personal_account.models.validate_price], verbose_name='Стоимость объекта при переходе в очередь'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=30, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁ]+$', 'Отчество может содержать только русские буквы')], verbose_name='Отчество'),
        ),
    ]
