# Generated by Django 5.2.4 on 2025-09-14 19:01

import personal_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0027_alter_historicalprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='parther_phone',
            field=models.CharField(blank=True, default='', max_length=12, validators=[personal_account.models.validate_phone], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parther_phone',
            field=models.CharField(blank=True, default='', max_length=12, validators=[personal_account.models.validate_phone], verbose_name='Номер телефона'),
        ),
    ]
